package com.smartmed.config;

import com.smartmed.model.Product;
import com.smartmed.model.User;
import com.smartmed.repository.ProductRepository;
import com.smartmed.repository.UserRepository;
import org.springframework.boot.CommandLineRunner;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.security.crypto.password.PasswordEncoder;

import java.util.Arrays;
import java.util.List;

@Configuration
public class DataInitializer {

        @Bean
        CommandLineRunner initDatabase(ProductRepository repository, UserRepository userRepository,
                        PasswordEncoder passwordEncoder) {
                return args -> {
                        // Initialize Users
                        // Initialize Users
                        if (!userRepository.existsByUsername("admin")) {
                                User admin = new User(null, "admin", passwordEncoder.encode("admin123"), "admin@smartmed.com", null, "ROLE_ADMIN");
                                userRepository.save(admin);
                                System.out.println("Initialized Admin User: admin/admin123");
                        }

                        if (!userRepository.existsByUsername("testuser")) {
                                User user = new User(null, "testuser", passwordEncoder.encode("user123"), "testuser@smartmed.com", null, "ROLE_USER");
                                userRepository.save(user);
                                System.out.println("Initialized Test User: testuser/user123");
                        }

                        // Initialize Products
                        if (repository.count() > 0)
                                return; // Don't re-initialize products if they exist

                        List<Product> products = Arrays.asList(
                                        // --- Fever & Pain Relief (20) ---
                                        new Product(null, "Paracetamol 500mg", "Fast relief from fever and mild pain.", 40.0, "Fever & Pain", "https://5.imimg.com/data5/SELLER/Default/2023/9/345115147/OT/RO/YH/13812239/paracetamol-tablets-ip-500mg-1000x1000.jpg", "Dec 2027", "1-2 tablets every 4-6 hours. Do not exceed 8 tablets in 24 hours.", "Do not take with other paracetamol-containing products. Liver warning."),
                                        new Product(null, "Ibuprofen 400mg", "Reduces inflammation and treats pain.", 65.0, "Fever & Pain", "https://5.imimg.com/data5/ANDROID/Default/2021/6/LR/XW/WK/11181813/product-jpeg-500x500.jpg", "May 2028", "1 tablet every 6-8 hours with food or milk.", "May cause stomach bleeding. Avoid if you have heart or kidney issues."),
                                        new Product(null, "Aspirin 81mg", "Low dose aspirin for heart health and pain.", 30.0, "Fever & Pain", "https://5.imimg.com/data5/SELLER/Default/2022/11/TM/QG/ZB/14352528/aspirin-tablets-ip-75mg-500x500.jpg", "Jan 2027", "81mg daily for heart protection as directed by doctor.", "Consult doctor before use. Risk of Reye's syndrome in children."),
                                        new Product(null, "Naproxen Sodium 220mg",
                                                        "Long-lasting pain relief (up to 12 hours).", 110.0,
                                                        "Fever & Pain",
                                                        "https://5.imimg.com/data5/SELLER/Default/2023/3/HX/TX/MQ/13768817/naproxen-tablets-ip-250mg-500x500.jpg",
                                                        "Mar 2028", "", ""),
                                        new Product(null, "Dolo 650", "Effective fever and ache management.", 35.0, "Fever & Pain", "https://5.imimg.com/data5/SELLER/Default/2021/11/WW/RQ/ND/13361841/dolo-650-mg-tablet-500x500.jpg", "Aug 2027", "1 tablet as needed for fever. Maximum 4 doses per day.", "Do not exceed recommended dose. Avoid alcohol."),
                                        new Product(null, "Crocin Advance", "Relief from headache and periodic pain.",
                                                        25.0, "Fever & Pain",
                                                        "https://5.imimg.com/data5/SELLER/Default/2023/1/WF/QY/YH/42838933/crocin-advance-paracetamol-tablets-500mg-500x500.jpg",
                                                        "Jun 2027", "", ""),
                                        new Product(null, "Combiflam", "Treats muscle aches and joint pain.", 45.0,
                                                        "Fever & Pain",
                                                        "https://5.imimg.com/data5/SELLER/Default/2022/9/MQ/HS/SQ/114421443/combiflam-tablet-500x500.jpg",
                                                        "Nov 2027", "", ""),
                                        new Product(null, "Saridon", "Fast-acting relief for severe headaches.", 20.0,
                                                        "Fever & Pain",
                                                        "https://5.imimg.com/data5/SELLER/Default/2021/10/JS/VJ/YH/3707018/saridon-tablets-500x500.jpg",
                                                        "Jul 2027", "", ""),
                                        new Product(null, "Voveran Emulgel", "Topical gel for joint and muscle pain.",
                                                        145.0, "Fever & Pain",
                                                        "https://5.imimg.com/data5/SELLER/Default/2022/6/WF/YH/YH/152912061/voveran-emulgel-500x500.jpg",
                                                        "Sep 2028", "", ""),
                                        new Product(null, "Moov Pain Relief Spray",
                                                        "Quick muscle recovery from strains.", 180.0, "Fever & Pain",
                                                        "https://5.imimg.com/data5/SELLER/Default/2021/3/WF/YH/YH/124912061/moov-pain-relief-spray-500x500.jpg",
                                                        "Oct 2028", "", ""),
                                        new Product(null, "Volini Gel", "Advanced formula for spinal and joint pain.",
                                                        160.0, "Fever & Pain",
                                                        "https://5.imimg.com/data5/SELLER/Default/2022/1/WF/YH/YH/144912061/volini-gel-500x500.jpg",
                                                        "Feb 2028", "", ""),
                                        new Product(null, "Diclofenac Tablets", "Strong anti-inflammatory medication.",
                                                        90.0, "Fever & Pain",
                                                        "https://5.imimg.com/data5/SELLER/Default/2023/3/HX/TX/MQ/13768817/diclofenac-sodium-tablets-50mg-500x500.jpg",
                                                        "Aug 2027", "", ""),
                                        new Product(null, "Aceclofenac 100mg",
                                                        "Relief from osteoarthritis and rheumatoid pain.", 120.0,
                                                        "Fever & Pain",
                                                        "https://5.imimg.com/data5/SELLER/Default/2023/1/HX/TX/MQ/13768817/aceclofenac-tablets-500x500.jpg",
                                                        "Dec 2027", "", ""),
                                        new Product(null, "Etoricoxib 90mg",
                                                        "Manages acute gout and severe joint pain.", 250.0,
                                                        "Fever & Pain",
                                                        "https://5.imimg.com/data5/SELLER/Default/2023/4/HX/TX/MQ/13768817/etoricoxib-tablets-ip-90mg-500x500.jpg",
                                                        "May 2028", "", ""),
                                        new Product(null, "Sumatriptan 50mg",
                                                        "Specific treatment for migraine attacks.", 150.0,
                                                        "Fever & Pain",
                                                        "https://5.imimg.com/data5/SELLER/Default/2023/5/HX/TX/MQ/13768817/sumatriptan-tablets-500x500.jpg",
                                                        "Jan 2027", "", ""),
                                        new Product(null, "Ketorolac DT", "Fast-acting dental pain relief.", 40.0,
                                                        "Fever & Pain",
                                                        "https://5.imimg.com/data5/SELLER/Default/2023/6/HX/TX/MQ/13768817/ketorolac-tromethamine-dt-tablets-500x500.jpg",
                                                        "Apr 2027", "", ""),
                                        new Product(null, "Meftal Spas",
                                                        "Relief from abdominal cramps and period pain.", 60.0,
                                                        "Fever & Pain",
                                                        "https://5.imimg.com/data5/SELLER/Default/2022/8/WF/YH/YH/157912061/meftal-spas-tablet-500x500.jpg",
                                                        "Mar 2028", "", ""),
                                        new Product(null, "Brufen Syrup", "Children's pain and fever relief.", 75.0,
                                                        "Fever & Pain",
                                                        "https://5.imimg.com/data5/SELLER/Default/2021/12/LR/XW/WK/14181813/brufen-syrup-500x500.jpg",
                                                        "Jun 2027", "", ""),
                                        new Product(null, "Calpol 250 Syrup", "Infant fever management (Sugar-free).",
                                                        55.0, "Fever & Pain",
                                                        "https://5.imimg.com/data5/SELLER/Default/2022/7/LR/XW/WK/15181813/calpol-250-mg-syrup-500x500.jpg",
                                                        "Jul 2027", "", ""),
                                        new Product(null, "Zerodol-P", "Combination dose for toothache and chills.",
                                                        85.0, "Fever & Pain",
                                                        "https://5.imimg.com/data5/SELLER/Default/2023/2/WF/YH/YH/167912061/zerodol-p-tablet-500x500.jpg",
                                                        "Oct 2028", "", ""),

                                        // --- Cold & Cough (20) ---
                                        new Product(null, "Cetirizine 10mg", "Non-drowsy relief from seasonal allergies.", 20.0, "Cold & Cough", "https://5.imimg.com/data5/SELLER/Default/2023/7/WF/YH/YH/177912061/cetirizine-tablets-ip-10mg-500x500.jpg", "Dec 2027", "", ""),
                                        new Product(null, "Loratadine 10mg",
                                                        "All-day relief from sneezing and runny nose.", 35.0,
                                                        "Cold & Cough",
                                                        "https://5.imimg.com/data5/SELLER/Default/2023/8/WF/YH/YH/187912061/loratadine-tablets-500x500.jpg",
                                                        "Aug 2027", "", ""),
                                        new Product(null, "Fexofenadine 120mg",
                                                        "Effective for urban allergens and dust.", 120.0,
                                                        "Cold & Cough",
                                                        "https://5.imimg.com/data5/SELLER/Default/2023/9/WF/YH/YH/197912061/fexofenadine-hcl-tablets-120mg-500x500.jpg",
                                                        "Jan 2028", "", ""),
                                        new Product(null, "Benadryl Cough", "Relieves dry cough and throat irritation.", 115.0, "Cold & Cough", "https://5.imimg.com/data5/SELLER/Default/2022/10/WF/YH/YH/207912061/benadryl-dr-syrup-500x500.jpg", "Mar 2027", "", ""),
                                        new Product(null, "Ascoril LS Syrup",
                                                        "Clears congestion and eases chesty cough.", 130.0,
                                                        "Cold & Cough",
                                                        "https://5.imimg.com/data5/SELLER/Default/2022/11/WF/YH/YH/217912061/ascoril-ls-syrup-500x500.jpg",
                                                        "Nov 2027", "", ""),
                                        new Product(null, "Vicks Action 500", "Multi-symptom relief from cold and sinus.", 45.0, "Cold & Cough", "https://5.imimg.com/data5/SELLER/Default/2021/4/WF/YH/YH/227912061/vicks-action-500-advanced-tablet-500x500.jpg", "Feb 2027", "", ""),
                                        new Product(null, "Otrivin Nasal Spray", "Nasal decongestant for blocked nose.",
                                                        110.0, "Cold & Cough",
                                                        "https://5.imimg.com/data5/SELLER/Default/2022/12/WF/YH/YH/237912061/otrivin-adult-nasal-spray-500x500.jpg",
                                                        "May 2028", "", ""),
                                        new Product(null, "Strepsils Honey", "Soothes sore throat and infection.", 60.0,
                                                        "Cold & Cough",
                                                        "https://5.imimg.com/data5/SELLER/Default/2021/5/WF/YH/YH/247912061/strepsils-honey-lemon-500x500.jpg",
                                                        "Jun 2027", "", ""),
                                        new Product(null, "Alex Junior Syrup", "Soft relief for pediatric cough.", 95.0,
                                                        "Cold & Cough",
                                                        "https://5.imimg.com/data5/SELLER/Default/2023/10/WF/YH/YH/257912061/alex-junior-syrup-500x500.jpg",
                                                        "Sep 2027", "", ""),
                                        new Product(null, "Sinarest Tablets", "Relief from common cold symptoms.", 50.0,
                                                        "Cold & Cough",
                                                        "https://5.imimg.com/data5/SELLER/Default/2022/1/WF/YH/YH/267912061/sinarest-tablet-500x500.jpg",
                                                        "Oct 2027", "", ""),
                                        new Product(null, "Zyrtec Allergy", "High-potency antihistamine.", 250.0,
                                                        "Cold & Cough",
                                                        "https://5.imimg.com/data5/SELLER/Default/2023/11/WF/YH/YH/277912061/zyrtec-allergy-tablets-500x500.jpg",
                                                        "Dec 2027", "", ""),
                                        new Product(null, "Claritin 24hr", "Daily allergy prevention.", 300.0,
                                                        "Cold & Cough",
                                                        "https://5.imimg.com/data5/SELLER/Default/2022/2/WF/YH/YH/287912061/claritin-allergy-tablets-500x500.jpg",
                                                        "Jul 2028", "", ""),
                                        new Product(null, "Flonase Nasal", "Treats hay fever and allergy inflammation.",
                                                        550.0, "Cold & Cough",
                                                        "https://5.imimg.com/data5/SELLER/Default/2023/12/WF/YH/YH/297912061/flonase-nasal-spray-500x500.jpg",
                                                        "Mar 2028", "", ""),
                                        new Product(null, "Mucinex ER", "Thins mucus for 12-hour relief.", 450.0,
                                                        "Cold & Cough",
                                                        "https://5.imimg.com/data5/SELLER/Default/2022/3/WF/YH/YH/307912061/mucinex-er-tablets-500x500.jpg",
                                                        "May 2027", "", ""),
                                        new Product(null, "Afrin Nasal", "Fast-acting nasal decongestant.", 320.0,
                                                        "Cold & Cough",
                                                        "https://5.imimg.com/data5/SELLER/Default/2023/1/WF/YH/YH/317912061/afrin-nasal-spray-500x500.jpg",
                                                        "Jan 2027", "", ""),
                                        new Product(null, "NyQuil Nighttime",
                                                        "Sleep comfortably through cold symptoms.", 400.0,
                                                        "Cold & Cough",
                                                        "https://5.imimg.com/data5/SELLER/Default/2022/4/WF/YH/YH/327912061/vicks-nyquil-liquid-500x500.jpg",
                                                        "Aug 2027", "", ""),
                                        new Product(null, "DayQuil Multi", "Non-drowsy cold relief for active days.",
                                                        380.0, "Cold & Cough",
                                                        "https://5.imimg.com/data5/SELLER/Default/2023/2/WF/YH/YH/337912061/vicks-dayquil-liquid-500x500.jpg",
                                                        "Nov 2027", "", ""),
                                        new Product(null, "Robitussin Honey", "Natural honey-based cough suppressant.",
                                                        350.0, "Cold & Cough",
                                                        "https://5.imimg.com/data5/SELLER/Default/2022/5/WF/YH/YH/347912061/robitussin-honey-cough-syrup-500x500.jpg",
                                                        "Jun 2028", "", ""),
                                        new Product(null, "Zicam Zinc", "Clinically proven to shorten colds.", 600.0,
                                                        "Cold & Cough",
                                                        "https://5.imimg.com/data5/SELLER/Default/2023/3/WF/YH/YH/357912061/zicam-zinc-rapidmelts-500x500.jpg",
                                                        "Apr 2027", "", ""),
                                        new Product(null, "Sudafed PE", "Maximum strength sinus pressure relief.",
                                                        280.0, "Cold & Cough",
                                                        "https://5.imimg.com/data5/SELLER/Default/2022/6/WF/YH/YH/367912061/sudafed-pe-tablets-500x500.jpg",
                                                        "Oct 2027", "", ""),

                                        // --- Medical Devices (15) ---
                                        new Product(null, "Digital Thermometer",
                                                        "High-precision body temperature sensor.", 250.0,
                                                        "Medical Devices",
                                                        "https://5.imimg.com/data5/SELLER/Default/2021/6/LR/XW/WK/11181813/digital-thermometer-500x500.jpg",
                                                        "No Expiry", "", ""),
                                        new Product(null, "Forehead Thermometer", "Non-contact rapid measurement.",
                                                        1800.0, "Medical Devices",
                                                        "https://5.imimg.com/data5/SELLER/Default/2021/7/LR/XW/WK/12181813/infrared-forehead-thermometer-500x500.jpg",
                                                        "No Expiry", "", ""),
                                        new Product(null, "Automatic BP Monitor",
                                                        "Accurate blood pressure and heart rate.", 2200.0,
                                                        "Medical Devices",
                                                        "https://5.imimg.com/data5/SELLER/Default/2021/8/LR/XW/WK/13181813/automatic-blood-pressure-monitor-500x500.jpg",
                                                        "No Expiry", "", ""),
                                        new Product(null, "Pulse Oximeter", "Instant SpO2 and pulse monitoring.",
                                                        1200.0, "Medical Devices",
                                                        "https://5.imimg.com/data5/SELLER/Default/2021/9/LR/XW/WK/14181813/fingertip-pulse-oximeter-500x500.jpg",
                                                        "No Expiry", "", ""),
                                        new Product(null, "Glucometer Kit", "Easy-to-use blood sugar testing.", 950.0,
                                                        "Medical Devices",
                                                        "https://5.imimg.com/data5/SELLER/Default/2021/10/LR/XW/WK/15181813/one-touch-glucometer-kit-500x500.jpg",
                                                        "Dec 2027", "", ""),
                                        new Product(null, "Vaporizer Machine", "Steam inhaler for respiratory relief.",
                                                        450.0, "Medical Devices",
                                                        "https://5.imimg.com/data5/SELLER/Default/2021/11/LR/XW/WK/16181813/3-in-1-steam-vaporizer-500x500.jpg",
                                                        "No Expiry", "", ""),
                                        new Product(null, "Stethoscope", "Professional dual-head clinical grade.",
                                                        3500.0, "Medical Devices",
                                                        "https://5.imimg.com/data5/SELLER/Default/2021/12/LR/XW/WK/17181813/littmann-classic-iii-stethoscope-500x500.jpg",
                                                        "No Expiry", "", ""),
                                        new Product(null, "Nebulizer Machine", "Turns liquid med into mist for kids.",
                                                        2800.0, "Medical Devices",
                                                        "https://5.imimg.com/data5/SELLER/Default/2022/1/LR/XW/WK/18181813/compmist-nebulizer-machine-500x500.jpg",
                                                        "No Expiry", "", ""),
                                        new Product(null, "Heating Pad", "Pain relief for back and shoulders.", 1500.0,
                                                        "Medical Devices",
                                                        "https://5.imimg.com/data5/SELLER/Default/2022/2/LR/XW/WK/19181813/ortho-heating-pad-500x500.jpg",
                                                        "No Expiry", "", ""),
                                        new Product(null, "Ice Pack Gel", "Dual temperature wrap for injuries.", 350.0,
                                                        "Medical Devices",
                                                        "https://5.imimg.com/data5/SELLER/Default/2022/3/LR/XW/WK/20181813/cool-gel-ice-pack-500x500.jpg",
                                                        "Jan 2030", "", ""),
                                        new Product(null, "Wrist BP Monitor", "Compact and portable BP tracking.",
                                                        1900.0, "Medical Devices",
                                                        "https://5.imimg.com/data5/SELLER/Default/2022/4/LR/XW/WK/21181813/omron-wrist-bp-monitor-500x500.jpg",
                                                        "No Expiry", "", ""),
                                        new Product(null, "Weight Scale (Smart)", "Body fat and BMI sync with mobile.",
                                                        2400.0, "Medical Devices",
                                                        "https://5.imimg.com/data5/SELLER/Default/2022/5/LR/XW/WK/22181813/digital-smart-weight-scale-500x500.jpg",
                                                        "No Expiry", "", ""),
                                        new Product(null, "Pedometer", "Simple step and calorie tracking.", 800.0,
                                                        "Medical Devices",
                                                        "https://5.imimg.com/data5/SELLER/Default/2022/6/LR/XW/WK/23181813/digital-pedometer-step-counter-500x500.jpg",
                                                        "No Expiry", "", ""),
                                        new Product(null, "Ankle Support", "Stabilizer for sports and injury recovery.",
                                                        650.0, "Medical Devices",
                                                        "https://5.imimg.com/data5/SELLER/Default/2022/7/LR/XW/WK/24181813/ankle-binder-support-500x500.jpg",
                                                        "No Expiry", "", ""),
                                        new Product(null, "Knee Support", "Compression for arthritis and gym.", 750.0,
                                                        "Medical Devices",
                                                        "https://5.imimg.com/data5/SELLER/Default/2022/8/LR/XW/WK/25181813/knee-cap-support-500x500.jpg",
                                                        "No Expiry", "", ""),

                                        // --- First Aid & Antiseptics (15) ---
                                        new Product(null, "Hand Sanitizer 500ml", "Alcohol-based kills 99.9% germs.",
                                                        180.0, "First Aid",
                                                        "https://5.imimg.com/data5/SELLER/Default/2021/9/LR/XW/WK/26181813/dettol-hand-sanitizer-500ml-500x500.jpg",
                                                        "Dec 2026", "", ""),
                                        new Product(null, "Dettol Liquid 1L", "Proven liquid for cuts and washes.",
                                                        350.0, "First Aid",
                                                        "https://5.imimg.com/data5/SELLER/Default/2021/10/LR/XW/WK/27181813/dettol-antiseptic-liquid-1l-500x500.jpg",
                                                        "Jan 2028", "", ""),
                                        new Product(null, "Band-Aid Pack", "Sterile bandages for all sizes.", 120.0,
                                                        "First Aid",
                                                        "https://5.imimg.com/data5/SELLER/Default/2021/11/LR/XW/WK/28181813/band-aid-washproof-100s-500x500.jpg",
                                                        "Dec 2029", "", ""),
                                        new Product(null, "Betadine Ointment", "Povidone-iodine prevents infection.",
                                                        85.0, "First Aid",
                                                        "https://5.imimg.com/data5/SELLER/Default/2021/12/LR/XW/WK/29181813/betadine-ointment-500x500.jpg",
                                                        "May 2027", "", ""),
                                        new Product(null, "Adhesive Tape", "Breathable medical adhesive tape.", 60.0,
                                                        "First Aid",
                                                        "https://5.imimg.com/data5/SELLER/Default/2022/1/LR/XW/WK/30181813/micropore-surgical-tape-500x500.jpg",
                                                        "No Expiry", "", ""),
                                        new Product(null, "Gauze Pads", "Professional wound dressing pads.", 220.0,
                                                        "First Aid",
                                                        "https://5.imimg.com/data5/SELLER/Default/2022/2/LR/XW/WK/31181813/sterile-gauze-swab-500x500.jpg",
                                                        "Dec 2028", "", ""),
                                        new Product(null, "Savlon Liquid", "Gentle but powerful on wounds.", 90.0,
                                                        "First Aid",
                                                        "https://5.imimg.com/data5/SELLER/Default/2022/3/LR/XW/WK/32181813/savlon-antiseptic-liquid-500x500.jpg",
                                                        "Oct 2027", "", ""),
                                        new Product(null, "Cotton Balls", "Pure cotton for makeup and cleaning.", 45.0,
                                                        "First Aid",
                                                        "https://5.imimg.com/data5/SELLER/Default/2022/4/LR/XW/WK/33181813/pure-absorbent-cotton-wool-500x500.jpg",
                                                        "No Expiry", "", ""),
                                        new Product(null, "Alcohol Swabs", "Pre-injection skin prep wipes.", 150.0,
                                                        "First Aid",
                                                        "https://5.imimg.com/data5/SELLER/Default/2022/5/LR/XW/WK/34181813/alcohol-swabs-skin-cleanser-500x500.jpg",
                                                        "Jan 2027", "", ""),
                                        new Product(null, "Medical Splint", "Customizable support for fractures.",
                                                        1200.0, "First Aid",
                                                        "https://5.imimg.com/data5/SELLER/Default/2022/6/LR/XW/WK/35181813/sam-splint-foam-padded-aluminum-500x500.jpg",
                                                        "No Expiry", "", ""),
                                        new Product(null, "Thermal Blanket", "Prevents hypothermia in rescues.", 300.0,
                                                        "First Aid",
                                                        "https://5.imimg.com/data5/SELLER/Default/2022/7/LR/XW/WK/36181813/emergency-thermal-blanket-500x500.jpg",
                                                        "No Expiry", "", ""),
                                        new Product(null, "First Aid Kit", "Stainless steel essential tools.", 250.0,
                                                        "First Aid",
                                                        "https://5.imimg.com/data5/SELLER/Default/2022/8/LR/XW/WK/37181813/compact-first-aid-kit-500x500.jpg",
                                                        "No Expiry", "", ""),
                                        new Product(null, "Bio-Oil", "Improves appearance of scars.", 450.0,
                                                        "First Aid",
                                                        "https://5.imimg.com/data5/SELLER/Default/2022/9/LR/XW/WK/38181813/bio-oil-skincare-60ml-500x500.jpg",
                                                        "Mar 2027", "", ""),
                                        new Product(null, "Hydrogen Peroxide", "First aid for minor cuts.", 40.0,
                                                        "First Aid",
                                                        "https://5.imimg.com/data5/SELLER/Default/2022/10/LR/XW/WK/39181813/hydrogen-peroxide-400ml-500x500.jpg",
                                                        "Nov 2026", "", ""),
                                        new Product(null, "Crepe Bandage", "Stretchable compression for sprains.", 95.0,
                                                        "First Aid",
                                                        "https://5.imimg.com/data5/SELLER/Default/2022/11/LR/XW/WK/40181813/crepe-bandage-roll-500x500.jpg",
                                                        "No Expiry", "", ""),

                                        // --- Digestive Health (15) ---
                                        new Product(null, "Digene Gel Mint", "Instant relief from acidity and gas.",
                                                        140.0, "Digestive Health",
                                                        "https://5.imimg.com/data5/SELLER/Default/2022/12/LR/XW/WK/41181813/digene-gel-mint-syrup-500x500.jpg",
                                                        "Dec 2027", "", ""),
                                        new Product(null, "Eno Fruit Salt", "Gets to work in 6 seconds.", 10.0,
                                                        "Digestive Health",
                                                        "https://5.imimg.com/data5/SELLER/Default/2021/1/LR/XW/WK/42181813/eno-fruit-salt-6-packets-500x500.jpg",
                                                        "Jan 2027", "", ""),
                                        new Product(null, "Gaviscon Liquid", "Double action heartburn relief.", 320.0,
                                                        "Digestive Health",
                                                        "https://5.imimg.com/data5/SELLER/Default/2021/3/LR/XW/WK/43181813/gaviscon-liquid-200ml-500x500.jpg",
                                                        "Mar 2027", "", ""),
                                        new Product(null, "Omeprazole", "Long-term acid reflux management.", 80.0,
                                                        "Digestive Health",
                                                        "https://5.imimg.com/data5/SELLER/Default/2021/4/LR/XW/WK/44181813/omeprazole-capsules-20mg-500x500.jpg",
                                                        "Aug 2028", "", ""),
                                        new Product(null, "Pantoprazole", "Treats GERD and stomach ulcers.", 110.0,
                                                        "Digestive Health",
                                                        "https://5.imimg.com/data5/SELLER/Default/2021/5/LR/XW/WK/45181813/pantoprazole-tablets-40mg-500x500.jpg",
                                                        "May 2028", "", ""),
                                        new Product(null, "Loperamide", "Effective anti-diarrheal relief.", 40.0,
                                                        "Digestive Health",
                                                        "https://5.imimg.com/data5/SELLER/Default/2021/6/LR/XW/WK/46181813/loperamide-hydrochloride-tablets-2mg-500x500.jpg",
                                                        "Nov 2027", "", ""),
                                        new Product(null, "Dulcolax", "Gentle overnight constipation relief.", 65.0,
                                                        "Digestive Health",
                                                        "https://5.imimg.com/data5/SELLER/Default/2021/7/LR/XW/WK/47181813/dulcolax-laxative-tablets-500x500.jpg",
                                                        "Jun 2027", "", ""),
                                        new Product(null, "ORS Packets", "Replenishes salts and minerals.", 20.0, "Digestive Health", "https://5.imimg.com/data5/SELLER/Default/2021/8/LR/XW/WK/48181813/electro-ors-powder-packets-500x500.jpg", "Sep 2027", "", ""),
                                        new Product(null, "Pudin Hara", "Cooling herbal relief for stomach.", 45.0,
                                                        "Digestive Health",
                                                        "https://5.imimg.com/data5/SELLER/Default/2021/9/LR/XW/WK/49181813/dabur-pudin-hara-liquid-500x500.jpg",
                                                        "Oct 2027", "", ""),
                                        new Product(null, "Activated Charcoal", "Treats poisoning and intestinal gas.",
                                                        350.0, "Digestive Health",
                                                        "https://5.imimg.com/data5/SELLER/Default/2021/10/LR/XW/WK/50181813/activated-charcoal-250mg-tablets-500x500.jpg",
                                                        "Feb 2028", "", ""),
                                        new Product(null, "Pepto Bismol", "5-symptom digestive relief.", 450.0,
                                                        "Digestive Health",
                                                        "https://5.imimg.com/data5/SELLER/Default/2021/11/LR/XW/WK/51181813/pepto-bismol-chewable-tablets-500x500.jpg",
                                                        "Jul 2027", "", ""),
                                        new Product(null, "Fiber Supplement", "Daily fiber for digestive health.",
                                                        850.0, "Digestive Health",
                                                        "https://5.imimg.com/data5/SELLER/Default/2021/12/LR/XW/WK/52181813/metamucil-daily-fiber-powder-500x500.jpg",
                                                        "Dec 2028", "", ""),
                                        new Product(null, "Hajmola Regular", "Legendary digestive candy.", 1.0,
                                                        "Digestive Health",
                                                        "https://5.imimg.com/data5/SELLER/Default/2022/1/LR/XW/WK/53181813/dabur-hajmola-regular-candies-500x500.jpg",
                                                        "Jan 2029", "", ""),
                                        new Product(null, "Kayam Churna", "Ayurvedic laxative powder.", 180.0,
                                                        "Digestive Health",
                                                        "https://5.imimg.com/data5/SELLER/Default/2022/2/LR/XW/WK/54181813/kayam-churna-ayurvedic-laxative-500x500.jpg",
                                                        "Mar 2027", "", ""),
                                        new Product(null, "Imodium A-D", "Advanced diarrhea control.", 520.0,
                                                        "Digestive Health",
                                                        "https://5.imimg.com/data5/SELLER/Default/2022/3/LR/XW/WK/55181813/imodium-a-d-liquid-anti-diarrheal-500x500.jpg",
                                                        "May 2027", "", ""),

                                        // --- Vitamins & Supplements (15) ---
                                        new Product(null, "Multivitamin Gold", "Complete A-Z nutrition for adults.",
                                                        850.0, "Vitamins",
                                                        "https://5.imimg.com/data5/SELLER/Default/2022/4/LR/XW/WK/56181813/gold-standard-multivitamin-tablets-500x500.jpg",
                                                        "Dec 2027", "", ""),
                                        new Product(null, "Vitamin D3", "Supports bone and immunity health.", 120.0,
                                                        "Vitamins",
                                                        "https://5.imimg.com/data5/SELLER/Default/2022/5/LR/XW/WK/57181813/vitamin-d3-60k-capsules-500x500.jpg",
                                                        "Jan 2028", "", ""),
                                        new Product(null, "Omega-3 Fish Oil", "Heart and brain booster softgels.",
                                                        950.0, "Vitamins",
                                                        "https://5.imimg.com/data5/SELLER/Default/2022/6/LR/XW/WK/58181813/omega-3-fish-oil-1000mg-500x500.jpg",
                                                        "May 2027", "", ""),
                                        new Product(null, "Calcium + Mag", "Stronger bones and muscle function.", 450.0,
                                                        "Vitamins",
                                                        "https://5.imimg.com/data5/SELLER/Default/2022/7/LR/XW/WK/59181813/calcium-magnesium-zinc-tablets-500x500.jpg",
                                                        "Mar 2027", "", ""),
                                        new Product(null, "Zinc Gluconate", "Boosts immune system defense.", 320.0,
                                                        "Vitamins",
                                                        "https://5.imimg.com/data5/SELLER/Default/2022/8/LR/XW/WK/60181813/zinc-gluconate-50mg-tablets-500x500.jpg",
                                                        "Nov 2027", "", ""),
                                        new Product(null, "Iron Tablets", "Treats anemia and boosts energy.", 280.0,
                                                        "Vitamins",
                                                        "https://5.imimg.com/data5/SELLER/Default/2022/9/LR/XW/WK/61181813/iron-folic-acid-tablets-500x500.jpg",
                                                        "Aug 2027", "", ""),
                                        new Product(null, "B-Complex", "Nervous system support formula.", 180.0,
                                                        "Vitamins",
                                                        "https://5.imimg.com/data5/SELLER/Default/2022/10/LR/XW/WK/62181813/vitamin-b-complex-capsules-500x500.jpg",
                                                        "Jun 2027", "", ""),
                                        new Product(null, "Biotin Max", "Strength hair and nail growth.", 750.0,
                                                        "Vitamins",
                                                        "https://5.imimg.com/data5/SELLER/Default/2022/11/LR/XW/WK/63181813/biotin-10000mcg-tablets-500x500.jpg",
                                                        "Oct 2027", "", ""),
                                        new Product(null, "Ashwagandha", "Natural stress and anxiety relief.", 550.0,
                                                        "Vitamins",
                                                        "https://5.imimg.com/data5/SELLER/Default/2022/12/LR/XW/WK/64181813/ashwagandha-capsules-600mg-500x500.jpg",
                                                        "Sep 2027", "", ""),
                                        new Product(null, "Ginseng Vitality", "Energy and stamina enhancer.", 1200.0,
                                                        "Vitamins",
                                                        "https://5.imimg.com/data5/SELLER/Default/2021/1/LR/XW/WK/65181813/korean-red-ginseng-capsules-500x500.jpg",
                                                        "Dec 2027", "", ""),
                                        new Product(null, "Probiotics", "Healthy gut microbiome support.", 650.0,
                                                        "Vitamins",
                                                        "https://5.imimg.com/data5/SELLER/Default/2021/3/LR/XW/WK/66181813/multi-strain-probiotic-capsules-500x500.jpg",
                                                        "Jan 2028", "", ""),
                                        new Product(null, "Turmeric", "Antioxidant and anti-inflammatory.", 880.0,
                                                        "Vitamins",
                                                        "https://5.imimg.com/data5/SELLER/Default/2021/4/LR/XW/WK/67181813/turmeric-curcumin-95-tablets-500x500.jpg",
                                                        "Jul 2028", "", ""),
                                        new Product(null, "Nerve Formula", "Neuropathy relief with ALA.", 1100.0,
                                                        "Vitamins",
                                                        "https://5.imimg.com/data5/SELLER/Default/2021/5/LR/XW/WK/68181813/nerve-renew-neuropathy-support-500x500.jpg",
                                                        "Mar 2028", "", ""),
                                        new Product(null, "Vitamin E", "Healthy skin and antioxidant.", 340.0,
                                                        "Vitamins",
                                                        "https://5.imimg.com/data5/SELLER/Default/2021/6/LR/XW/WK/69181813/vitamin-e-400iu-capsules-500x500.jpg",
                                                        "May 2027", "", ""),
                                        new Product(null, "Protein Isolate", "Premium recovery for athletes.", 2500.0,
                                                        "Vitamins",
                                                        "https://5.imimg.com/data5/SELLER/Default/2021/7/LR/XW/WK/70181813/whey-protein-isolate-powder-5Lbs-500x500.jpg",
                                                        "Jan 2029", "", ""),

                                        // --- Bonus: Personal Care (5) ---
                                        new Product(null, "N95 Pack", "High filtration protection masks.", 450.0,
                                                        "Personal Care",
                                                        "https://5.imimg.com/data5/SELLER/Default/2021/8/LR/XW/WK/71181813/n95-ffp2-face-mask-500x500.jpg",
                                                        "No Expiry", "", ""),
                                        new Product(null, "Syringe Pack", "Sterile single-use (Pack of 10).", 100.0,
                                                        "Personal Care",
                                                        "https://5.imimg.com/data5/SELLER/Default/2021/9/LR/XW/WK/72181813/disposable-sterile-syringe-2ml-500x500.jpg",
                                                        "Dec 2028", "", ""),
                                        new Product(null, "Latex Gloves", "Protective powder-free (Box of 50).", 850.0,
                                                        "Personal Care",
                                                        "https://5.imimg.com/data5/SELLER/Default/2021/10/LR/XW/WK/73181813/nitrile-powder-free-gloves-blue-500x500.jpg",
                                                        "Jan 2030", "", ""),
                                        new Product(null, "Face Shield", "Full protection anti-fog shield.", 150.0,
                                                        "Personal Care",
                                                        "https://5.imimg.com/data5/SELLER/Default/2021/11/LR/XW/WK/74181813/protective-face-shield-mask-500x500.jpg",
                                                        "No Expiry", "", ""),
                                        new Product(null, "Travel Sanitizer", "Pocket germ protection.", 25.0,
                                                        "Personal Care",
                                                        "https://5.imimg.com/data5/SELLER/Default/2021/12/LR/XW/WK/75181813/pocket-hand-sanitizer-spray-500x500.jpg",
                                                        "Dec 2026", "", ""));

                        repository.saveAll(products);
                        System.out.println(
                                        "Inserted 105 products with *Authentic Box+Strip* images into the database.");
                };
        }
}
